### ISSUE TITLE
Enable login with Oauth2

### ISSUE THREAD

**Issue by ljmerza** [custom-components/usps_mail#10]
**Is your feature request related to a problem? Please describe.**
Please add oauth2 logins. I would have to disable 2 factor authentication for this to work with my gmail

**Describe the solution you'd like**
[Here is an example](https://github.com/google/gmail-oauth2-tools/blob/master/python/oauth2.py)

**Comment by ludeeus** [comment]
Disabling 2FA is bad, instead create a app password in your account settings and use that password here
