### ISSUE TITLE
package_count is included in "Informed Delivery Daily Digest" email

### ISSUE THREAD

**Issue by ljmerza** [custom-components/usps_mail#11]
**Version of the custom_component**

latest

**Describe the bug**
The list of packages comes as tracking link in the original "Informed Delivery Daily Digest" email not through the "auto-reply@usps.com" email.

**log**
no debugging log packages just always show up as 0

<img width="750" alt="capture" src="https://user-images.githubusercontent.com/4085765/51720854-555fe880-201d-11e9-894c-cf2bac3a310f.PNG">

**Comment by ljmerza** [comment]
Still an issue please don't close

**Comment by brmonaghan** [comment]
Still an issue please don't close
This seems to happen on my USPS ID too.

**Comment by maykar** [comment]
This component has been abandoned for quite some time. A new component and card has been made by different authors and is still actively developed. You can find it's [component here](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages), [card here](https://github.com/moralmunky/Home-Assistant-Mail-And-Packages-Custom-Card), and [forum thread here](https://community.home-assistant.io/t/mail-and-packages-custom-component-for-ups-fedex-and-usps/118081).

**Comment by brmonaghan** [comment]
Ok.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
